# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Keyboard: PseudoCorne
  - keyboard: PseudoCorne
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-corne-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoCorne\"
  - keyboard: PseudoCorne
    board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: zmk-corne-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoCorne\"
  - keyboard: PseudoCorne
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-corne-settings-reset

  # Keyboard: PseudoLilCorne
  - keyboard: PseudoLilCorne
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-lil-corne-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"
  - keyboard: PseudoLilCorne
    board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: zmk-lil-corne-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"
  - keyboard: PseudoLilCorne
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-lil-corne-settings-reset

  # Keyboard: PseudoLily58
  - keyboard: PseudoLily58
    board: mikoto@7.2
    shield: lily58_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-lily58-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLily58\"
  - keyboard: PseudoLily58
    board: mikoto@7.2
    shield: lily58_right nice_view_adapter nice_view
    artifact-name: zmk-lily58-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLily58\"
  - keyboard: PseudoLily58
    board: mikoto@7.2
    shield: settings_reset
    artifact-name: zmk-lily58-settings-reset
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"
