# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Keyboard: PseudoLily58 (nicenano)
  - keyboard: PseudoLily58
    board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view_thorne
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-nicenano-lily58-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLily58\"
  - keyboard: PseudoLily58
    board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view_thorne
    artifact-name: zmk-nicenano-lily58-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLily58\"
  - keyboard: PseudoLily58
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-nicenano-lily58-settings-reset
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"

  # Keyboard: PseudoLily58 (mikoto)
  - keyboard: PseudoLily58
    board: mikoto@7.2
    shield: lily58_left nice_view_adapter nice_view_thorne
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-mikoto-lily58-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLily58\"
  - keyboard: PseudoLily58
    board: mikoto@7.2
    shield: lily58_right nice_view_adapter nice_view_thorne
    artifact-name: zmk-mikoto-lily58-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLily58\"
  - keyboard: PseudoLily58
    board: mikoto@7.2
    shield: settings_reset
    artifact-name: zmk-mikoto-lily58-settings-reset
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"

  # Keyboard: PseudoCorne (nicenano)
  - keyboard: PseudoCorne
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_thorne
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-nicenano-corne-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoCorne\"
  - keyboard: PseudoCorne
    board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_thorne
    artifact-name: zmk-nicenano-corne-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoCorne\"
  - keyboard: PseudoCorne
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-nicenano-corne-settings-reset

  # Keyboard: PseudoCorne (mikoto)
  - keyboard: PseudoCorne
    board: mikoto@7.2
    shield: corne_left nice_view_adapter nice_view_thorne
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-mikoto-corne-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoCorne\"
  - keyboard: PseudoCorne
    board: mikoto@7.2
    shield: corne_right nice_view_adapter nice_view_thorne
    artifact-name: zmk-mikoto-corne-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoCorne\"
  - keyboard: PseudoCorne
    board: mikoto@7.2
    shield: settings_reset
    artifact-name: zmk-mikoto-corne-settings-reset

  # Keyboard: PseudoLilCorne (nicenano)
  - keyboard: PseudoLilCorne
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_thorne
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-nicenano-lil-corne-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"
  - keyboard: PseudoLilCorne
    board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_thorne
    artifact-name: zmk-nicenano-lil-corne-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"
  - keyboard: PseudoLilCorne
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-nicenano-lil-corne-settings-reset

  # Keyboard: PseudoLilCorne (mikoto)
  - keyboard: PseudoLilCorne
    board: mikoto@7.2
    shield: corne_left nice_view_adapter nice_view_thorne
    snippet: studio-rpc-usb-uart # left only
    artifact-name: zmk-mikoto-lil-corne-left
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"
  - keyboard: PseudoLilCorne
    board: mikoto@7.2
    shield: corne_right nice_view_adapter nice_view_thorne
    artifact-name: zmk-mikoto-lil-corne-right
    cmake-args: |
      -DCONFIG_ZMK_KEYBOARD_NAME=\"PseudoLilCorne\"
  - keyboard: PseudoLilCorne
    board: mikoto@7.2
    shield: settings_reset
    artifact-name: zmk-mikoto-lil-corne-settings-reset

  # Keyboard: Reviung5
  - keyboard: PseudoReviung5
    board: nice_nano_v2
    shield: reviung5
    artifact-name: zmk-nicenano-reviung5
  - keyboard: PseudoReviung5
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-nicenano-reviung5-settings-reset
