manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pseudo-su
      url-base: https://github.com/pseudo-su
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-thorne
      remote: pseudo-su
      revision: main
  self:
    path: config
